<a href="https://colab.research.google.com/github/ReyFrank92/joyofcoding/blob/main/TF2_0_RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Install TensorFlow
!pip install -q tensorflow-gpu==2.9.0
import tensorflow as tf
print(tf.__version__)

     |████████████████████████████████| 511.7 MB 3.9 kB/s 
     |████████████████████████████████| 1.6 MB 42.4 MB/s 
     |████████████████████████████████| 5.8 MB 36.4 MB/s 
     |████████████████████████████████| 438 kB 66.4 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.2+zzzcolab20220527125636 requires keras<2.9,>=2.8.0rc0, but you have keras 2.9.0 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires tensorboard<2.9,>=2.8, but you have tensorboard 2.9.1 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires tensorflow-estimator<2.9,>=2.8, but you have tensorflow-estimator 2.9.0 which is incompatible.
2.9.0


In [2]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hideen units 
# K = number of output units

In [4]:
# make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [5]:
#Make an RNN
M = 5 # M = number of hidden units 
i = Input(shape = (T, D)) # T = sequence length # D = number of input features (10 row, 3 column)
x = SimpleRNN(M)(i) #i = (10,3)
x = Dense (K)(x) # K = number of output units #la x ya es el modelo en si

model = Model(i, x) #Aqui es una regresió porque no hay función de activación

In [8]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 16ms/step
[[-0.533558   -0.07396743]]


In [9]:
## See if we can replicate this output
# Get the weights first
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [10]:
# See what's returned []
model.layers[1].get_weights()

[array([[ 0.68565947, -0.79998595, -0.32234496, -0.04334271, -0.6400622 ],
        [-0.02203661,  0.45497626, -0.79826844,  0.15524656, -0.23784548],
        [ 0.31050497,  0.71541005,  0.8349348 ,  0.8178119 , -0.6329204 ]],
       dtype=float32),
 array([[ 0.00527501,  0.25545233,  0.44668296, -0.83709145,  0.1856568 ],
        [ 0.17507012,  0.3005518 ,  0.46854103,  0.48697641,  0.64987874],
        [-0.06958926,  0.90484744, -0.14976731,  0.11238919, -0.3759614 ],
        [-0.8002884 , -0.10017154,  0.50820404,  0.1821303 , -0.24095915],
        [ 0.5692261 , -0.12501821,  0.5479435 ,  0.12778503, -0.5863284 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [12]:
#Check tehir shapes
#should make sense
#First output is input > hidden
#Second output is hidden > hidden
#Thier output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape,b.shape,c.shape) # D = 3 and M = 5. (3,5) =  (D x M) i.e. input to hidden ; (5,5) = (M x M) head into head ; (5,)  = M (vector) bias term 

(3, 5) (5, 5) (5,)


In [13]:
Wx, Wh, bh = model.layers[1].get_weights() #Wxh - input to hidden weight // bh - hidden bias
Wo, bo = model.layers[2].get_weights() #Wo - hidden to output weight // bo - output bias

In [14]:
h_last = np.zeros(M) # initial hidden state [] #An array of 5 zeros because M =  5
x = X[0] #The one and only simple. Toma el primer valor en X
Yhats = [] # Where we store the outputs

for t in range(T): # corre de 1 a 10 xk T = 10
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh) #devuelve un resultado de una función de tangente hiperbólica dato el producto punto de una matriz en este caso los pesos Wx, Wx +bh
  y = h.dot(Wo) + bo #we only care about this value on the last iteration
  Yhats.append(y) #este es el Y estimado y se agrega al final de una variable definida Y

  #Important: assign h  to h_last
  h_last = h 

#print the final output
print(Yhats[-1])

[-0.53355803 -0.07396753]


In [ ]:
# bonus exercise: calculate the output for multiple samples at once (N > 1)